const courses = [
  {
    id: "1",
    levels: "Foundation + 8 Levels",
    imgsrc: "abacus.jpeg",
    title: "Abacus ",
    ageGroup: "6 to 15 Years",
    duration: "2 to 3 Months",
    description: "Master mental arithmetic with our Abacus course.",
    benefits: [
      "Mathematical Skills Development",
      "Enhanced Mental Arithmetic",
      "Improved Concentration and Focus",
      "Visualization & Multisensory Learning ",
    ],
    targetId: "abacus",
  },
  {
    id: "2",
    levels: "No Levels",
    imgsrc: "handwriting.jpeg",
    title: "Handwriting ",
    ageGroup: "6 to 15 Years",
    duration: "25 Classes",
    targetId: "handwriting",
    description:
      "Refine your handwriting with our Handwriting Improvement course.",
    benefits: [
      "Benefits and Results",
      "Boosted Self-Confidence",
      "Improved Fine Motor Skills",
      "Enhanced Cognitive Skills",
      "Life-long Skill",
    ],
  },
  {
    id: "3",
    levels: "8 Levels",
    ageGroup: "6 to 18 Years",
    imgsrc: "maths.jpeg",
    title: "Vedic Mathematics",
    duration: "2 to 3 months",
    targetId: "vedic-maths",
    description:
      "Dive into the world of Vedic Mathematics and unlock the power of faster calculations.",
    benefits: [
      "Speed and Efficiency",
      "Simplicity and Ease of Understanding",
      "Improved Mental Arithmetic Skills",
      "Enhanced Problem-Solving Skills",
    ],
  },
  {
    id: "4",
    levels: "2 Levels",
    imgsrc: "phonics.jpeg",
    title: "Phonics",
    ageGroup: "6 to 12 Years",
    duration: "3 months",
    targetId: "phonics",
    description: "Build literacy skills with our Phonics course.",
    benefits: [
      "Enhanced Vocabulary",
      "Increased Reading Comprehension",
      "Support for Struggling Readers",
      "Independence in Reading",
    ],
  },
  {
    id: "5",
    levels: "No Levels",
    imgsrc: "grammar.jpeg",
    title: "Grammar",
    ageGroup: "6 to 18 Years",
    duration: "4 to 5 months",
    targetId: "grammar",
    description:
      "Master the fundamentals of grammar with our Grammar Essentials course.",
    benefits: [
      "Clarity of Communication",
      "Enhanced Writing Skills",
      "Language Mastery",
      "Confidence in Speaking",
    ],
  },
  {
    id: "6",
    levels: "8 Levels",
    imgsrc: "abacus.jpeg",
    title: "Finger (Hand) Abacus",
    ageGroup: "6 to 15 Years",
    duration: "2 to 3 months",
    targetId: "abacus-hand",
    description:
      "Unlock the power of mental calculation with our Finger (Hand) Abacus course.",
    benefits: [
      "Improved Fine Motor Skills",
      "Visual and Spatial Reasoning",
      "Enhanced Photographic Memory",
      "Accessible Learning Tool",
      "Mathematical Fluency",
    ],
  },
];

export default courses;
